apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  kraft:
    enabled: true
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 20Gi
  configOverrides:
    server:
      - "num.partitions=6"
      - "default.replication.factor=3"
