apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: connect-hpa
  namespace: confluent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: connect
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
